### PR TITLE
Don't try to reconnect player when it disconnects manually

### PR DESCRIPTION
**Pull request by Raraph84**
I should solve the https://github.com/SpigotMC/BungeeCord/issues/3711 issue

### CODE REVIEW

**Comment by Raraph84** [comment]
(just signed the commit)

**Comment by Outfluencer** [comment]
i think the problem is that the server is not marked as obsolote as it should be

I would fix it by set obsolte to true if the server gets disconnected
This way the internal use of obsolete is more consistent
We also could remove any lines of code that set obsolote to true before disconnecting the server like this

`user.getServer().setObsolete( true );`
`user.getServer().disconnect( "Quitting" );`

**Comment by Raraph84** [comment]
Like that?
I tested and it works

**Comment by Outfluencer** [comment]
Yes thats exactly what was on my mind

**Comment by Raraph84** [comment]
I think this can be merged so

**Comment by md-5** [comment]
> i think the problem is that the server is not marked as obsolote as it should be
> 
> I would fix it by set obsolte to true if the server gets disconnected This way the internal use of obsolete is more consistent We also could remove any lines of code that set obsolote to true before disconnecting the server like this
> 
> `user.getServer().setObsolete( true );` `user.getServer().disconnect( "Quitting" );`
> 
> And just call the setObsolote inside the disconnect method

Are you sure this fixes it? Looking at the code ServerConnection#disconnect is already accompanied by a setObsolete

**Comment by Outfluencer** [comment]
> > i think the problem is that the server is not marked as obsolote as it should be
> > I would fix it by set obsolte to true if the server gets disconnected This way the internal use of obsolete is more consistent We also could remove any lines of code that set obsolote to true before disconnecting the server like this
> > `user.getServer().setObsolete( true );` `user.getServer().disconnect( "Quitting" );`
> > And just call the setObsolote inside the disconnect method
> 
> Are you sure this fixes it? Looking at the code ServerConnection#disconnect is already accompanied by a setObsolete

its about the          
   con.getServer().disconnect( "Quitting" ); call
in the Upstreambridge disconnected method
there we have not set obsolete to true

**Comment by Raraph84** [comment]
Can this be merged then?

**Pull request merged**
