### PR TITLE
Make glist command output hover and clickable

### PR DESCRIPTION
**Pull request by Outfluencer**
if clicked the player will be sent to the server he's  hovering

### CODE REVIEW

**Comment by Janmm14** [comment]
maybe check server restricted and if yes, the perm for that, before adding click event for a server

**Comment by Outfluencer** [comment]
I thought the server.canAccess check would do this for me

**Comment by md-5** [comment]
it does

**Comment by Janmm14** [comment]
Sorry, I didn't look at the unchanged code.

**Pull request closed without merging**
