### PR TITLE
[Forge] Allow passing of REGISTER messages from Client to Server at the right moment during the FML Handshake.

### PR DESCRIPTION
**Pull request by dualspiral**
Some mods rely on the channels being registered before Bungee normally gets around to it. This commit allows the required packets to go through, which are the ones in response to the ServerHello message. Without this, the REGISTER packets would be sent later - too late for some mods that rely on it.

I have tested this through debugging, the REGISTER messages are now being sent/passed on at the right time. Thanks to @boq for alerting me to this issue in #1248. 

A small amount of related cleanup has also been done.

### CODE REVIEW

**Comment by dualspiral** [comment]
Note - pulling this and #1283 will break the build, as I rename one of the constants so that the name reflects what the packet actually is. I would recommend that #1283 is pulled first (the importance of this patch is much lower than that one), I will fix this PR once that is done.

**Comment by tf101-wizard** [comment]
@dualspiral Is it really that complicated for people to change a constant :P

**Comment by dualspiral** [comment]
@tf101-wizard Considering the constant name shouldn't be changed, harder than you think! ;) In all seriousness though, I wanted to make sure that it's known, so the two PRs aren't pulled without thought and suddenly the Bungee CI build breaks spectacually - probably putting me in the doghouse!

**Comment by tf101-wizard** [comment]
This is true you don't want to be put it the doghouse of @md-5 i hear it has lots of chains and barbed wire! :P

**Pull request closed without merging**
