### PR TITLE
Removed console ping message

### PR DESCRIPTION
**Pull request by Fishy246**

### CODE REVIEW

**Comment by yawkat** [comment]
Why?

**Comment by Fishy246** [comment]
Because I find that it causes spam in the console, and if a significant amount of players are pinging the server it clutters the console up and makes it hard to find the things that are actually important

**Comment by yawkat** [comment]
I think this was denied in a previous issue

**Comment by lockerecca** [comment]
not sure. but good. idea try code.. new option on cfg put some case else etc in code.  i think if optional  and look good idea if you hate take some control.. who hell visit your network

**Comment by Fishy246** [comment]
@lockerecca Yeah, this was just a quick little edit. I am working on something more permanent now :)

**Comment by PhanaticD** [comment]
maybe make it configurable instead of straight up removing?

**Comment by Janmm14** [comment]
Another possiblity is just using gits power and have a custom fork you rebase on the current bungee version, if this get declined.

**Comment by Xayanix** [comment]
+1
annoying thing

**Comment by Janmm14** [comment]
without a config option this will not get accepted

**Comment by njb-said** [comment]
Is there a need for that log line?

**Comment by Fishy246** [comment]
@njb-said As far as I am aware, the only purpose could be debugging except for that it just causes unnecessary console spam

**Comment by Janmm14** [comment]
Look here: http://www.spigotmc.org/resources/quietcord.12940/

**Comment by md-5** [comment]
ba0739798a0b6f184eca4def52750e8633623487

**Pull request closed without merging**
