### PR TITLE
Updated to 1.13 release

### PR DESCRIPTION
**Pull request by nilsbrychzy**

### CODE REVIEW

**Comment by md-5** [comment]
Thanks, but Minecraft updates are handled internally and will be released in line with Bukkit/CraftBukkit/Spigot.

**Comment by Leymooo** [comment]
Sorry for reply, but this is not fully upgrade to 1.13. ScoreboardObjective and Teams now have a Json in prefix, suffix, etc.. (Chat component)
http://wiki.vg/Pre-release_protocol#Scoreboard_Objective

**Comment by md-5** [comment]
Its still a string at the protocol level.
Bungee technically does have a "scoreboard API" that maybe should be changed to convert into components, but the main purpose of the API is really just to allow bungee to wipe scoreboards on server switch.

**Comment by Leymooo** [comment]
Yes, but json string use a more memory that legacy text. Scoreboards use about 70-80% of memory in bungecord, and if store json string it will use more memory. 
How about to use TextComponent.toLegacyText (ComponentSerealizer.parse (...)). And ComponentSerealizer.toString(TextComponent.fromLegacyText(..)). For read and write. This will restore a ScoreBoard API for 1.13 for old plugins.

**Comment by md-5** [comment]
> Scoreboards use about 70-80% of memory in bungecord, and if store json string it will use more memory.

Only if you have some broken animated scoreboard plugin

**Pull request closed without merging**
