### PR TITLE
Fix Timed out issue

### PR DESCRIPTION
**Pull request by Dimatert9**
Server1 send keepAlive with id 9999
Player was moved to other server and server send again keepAlive with id 9999
if we doest not reset id, server will recieve 2 packets.

#2261

### CODE REVIEW

**Comment by md-5** [comment]
This cannot possibly fix anything in the current code

**Comment by md-5** [comment]
I do not think this is an issue.
The unique IDs are changed every millisecond.
So for this to be an issue both servers would need to send a keepalive within 0.5 millisecond of eachother.

Have you actually tested this change? Maybe the unsupported servers / plugins you are using are using a bad keepalive generation algorithm if this actually works

**Comment by Dimatert9** [comment]
I really do not understand how this happens. 
With this commit https://github.com/SpigotMC/BungeeCord/commit/3fa84f4bef960ddf5ee163b548125c7d31b945d1
bungeecord was launched all day. There is no timed out kicks.

**Comment by md-5** [comment]
Please don't propose PRs you don't understand then.
The commit you linked is broken, it breaks pings and defeats the purpose of the keepalive

**Comment by Dimatert9** [comment]
Sorry. When i launcher server with this commit there is no kicks. But now they returns;
I really dont know why this happened and how fix it now in BungeeCord.
Can you remove kick code from spigot in PlayerConnection?

**Comment by MinelandTeam** [comment]
Хочешь подскажу очень простой способ решения проблемы? Он костыльный, да. Но помогает.
Просто хукай через протоколиб, пакет кика, и если там причина таймаут - отменяй его. Важно делать это на всех серверах.

**Comment by md-5** [comment]
English

**Comment by Dimatert9** [comment]
Слушай. А ведь рили найс идея. Спасиба)

**Comment by Janmm14** [comment]
Best english of the world. :/

**Comment by Dimatert9** [comment]
Yeah)

**Pull request closed without merging**
