### PR TITLE
fix: inverted isEmpty method on ComponentStyle

### LINKED ISSUE #3610: ComponentStyle#isEmpty is inverted
### Bungeecord version

737d545fb60523bd7deafd5551f06615c0b87f0e

### Server version

_No response_

### Client version

_No response_

### Bungeecord plugins

None, this is a bug report related to code

### The bug

https://github.com/SpigotMC/BungeeCord/blob/02c5c1ee76cad1c09eed05028a66bfbae7cdebfb/chat/src/main/java/net/md_5/bungee/api/chat/ComponentStyle.java#L188-L198

The `ComponentStyle#isEmpty` function is inverted (returns `true` if component has styles).

### Easy tests to reproduce
image
```java
(new net.md_5.bungee.api.chat.ComponentStyle()).isEmpty()
```
returns `false`, but should return `true`

image
```java
(new net.md_5.bungee.api.chat.TextComponent()).hasFormatting()
```
returns `true`, should return `false`

I'll be submitting a PR shortly.

Related to PR #3569

### Log output (links)

_No response_

### Checking

- [X] I am using BungeeCord and **not a fork**. Issues with forks should not be reported here.
- [X] I think this is **not** an issue with a bungeecord plugin.
- [ ] I have not read these checkboxes and therefore I just ticked them all.
- [X] This is not a question or plugin creation help request.

### PR DESCRIPTION
**Pull request by diogotcorreia**
Fixes #3610
Relates to #3569 and 737d545fb60523bd7deafd5551f06615c0b87f0e

cc @2008Choco

### CODE REVIEW

**Comment by diogotcorreia** [comment]
Thanks, missed that :sweat_smile: 
Fixed and force pushed

**Comment by diogotcorreia** [comment]
Should I add some tests as well?
I can do that a few hours from now.

**Comment by md-5** [comment]
Yes a test would be great thanks

**Comment by diogotcorreia** [comment]
I've added two tests, let me know if you want more.
Ready to merge :tada:

**Comment by 2008Choco** [comment]
Thank you! I should have made a unit test for this method :)

**Pull request merged**
