### PR TITLE
Fix native-cipher segfault when using musl libc

### PR DESCRIPTION
**Pull request by lax1dude**
This fixes Issue #3707

mbedtls has some preprocessor directives that enable a glibc-specific implementation for zeroing out memory in the context free function, this causes a segfault when the binary run on a linux distro that doesn't use glibc, like Alpine. One fix is compiling the native cipher SO file on a musl-based distro so the glibc-specific implementation is disabled, but I found out that mbedtls also lets you override the zero-out function for situations like this, so I used that feature instead to replace it with an implementation that works on both glibc and musl.

To test it, I compiled native-cipher.so on a glibc-based system, then copied it into an Alpine Linux VM and ran `mvn test`. All the tests pass on both the glibc-based system and also using Alpine Linux using the same binary.

Additionally, I used a disassembler to make sure the memset wasn't being optimized away, and to check how many copies of my replacement zero function were created. Only 2 copies were created so I don't see any real issue with making the function static for our specific use.

### CODE REVIEW

**Comment by Rigner** [comment]
The code looks good, will test this on my setup in a few jours 👍

**Review by Rigner — COMMENTED** [review]
Tested it on the Alpine environment where it was crashing, after replacing the .so file with the new one everything works fine now. I can disconnect and rejoin without any issues.

👍

**Comment by xism4** [comment]
Works fine on Alpine

**Comment by md-5** [comment]
Is part of the issue that musl doesn't support memset_s?

**Comment by lax1dude** [comment]
@md-5 It was using `explicit_bzero` based on preprocessor directives that check for new versions of glibc at compile time. I believe it was using `memset_s` when I compiled it on musl.

Now that I think about it, I can't remember exactly why I shot down using `memset_s` for this PR, it's probably a better choice. I'll try revising this PR to use `memset_s` instead when I get home from work today, let's wait another day before merging.

**Comment by lax1dude** [comment]
I did more research and it looks like `memset_s` isn't even supported by glibc, so its not an option if we want to create universally compatible natives.

**Comment by lax1dude** [comment]
I made the native cipher zero out the key in the crypto_context struct when the context is free'd for a bit of added security, since otherwise the encryption key could be leaked by code reading uninitialized memory some time later after it was free'd.

**Review by md-5 — APPROVED** [review]

**Pull request closed without merging**
