### PR TITLE
Added a DisconnectReason to the ServerDisconnectEvent

### PR DESCRIPTION
**Pull request by ByteAlex**
So I added the possibility to check the DisconnectReason in the ServerDisconnectEvent.
Debug messages were successful. Im not fully into lombok, but i think, the event-class should be fine too.

Greetings
Alex

### CODE REVIEW

**Comment by scholzi100** [comment]
Nice feature

**Comment by original-codematrix** [comment]
Good idea!

**Comment by ApocalypsjeNL** [comment]
It's funny that you added 4 DisconnectReasons but only 3 are used in your code.

**Comment by xXAlex10Xx** [comment]
@ApocalypsjeNL Yeah really funny. I thought about which reasons i may need but forgot to remove the one i did not need.

Thanks for reporting this. Ill fix that.

**Comment by md-5** [comment]
This PR just assumes a whole lot of things that aren't true

* If any exception is caught by bungee, the server crashed
* If we weren't in a server change, then the connection was lost (what about player kicks etc)
* If the server crashed, then the connection was closed
* Otherwise the player was happily switching servers (also not true)

You can probably get away with the connection lost assumption and have two states - server switch and connection lost, but anything else is just pure guessing

**Pull request closed without merging**
