### PR TITLE
added command name tab completion to console

### PR DESCRIPTION
**Pull request by Outfluencer**
With this change we can tab complete the command names and not only the arguments

### CODE REVIEW

**Comment by md-5** [comment]
Why though? You can't chat in the console without a command

**Comment by Outfluencer** [comment]
It makes it much easier to see all available commands und you dont need to write the full name of the command like write a b and than press tab and it will tabcomplete to bungee
It makes the use of the console more easy and simple

**Comment by md-5** [comment]
Sorry I thought you meant player names from the title

**Comment by Outfluencer** [comment]
> Sorry I thought you meant player names from the title

Yeah sorry i think the title is more understandable now

**Comment by MrIvanPlays** [comment]
you may want to not use guava for filtering and mapping but java 8's stream api

**Comment by Outfluencer** [comment]
Hm in the PlayerCommand class its done the same way so i thought i do it like there

**Comment by MrIvanPlays** [comment]
> Hm in the PlayerCommand class its done the same way so i thought i do it like there

yeah but when the PlayerCommand class was written BungeeCord's minimal java version requirement wasn't java 8, also now this guava api is marked that it will be removed so let's not use it in any of the new code.

**Comment by MrIvanPlays** [comment]
> Were is it marked?

image

**Comment by Outfluencer** [comment]
Okey i will change it

**Comment by Outfluencer** [comment]
md-5 would you say we should replace all the old guava stuff with Java streams?

**Pull request closed without merging**
