### PR TITLE
Support multiples OpenSSL versions for native cipher

### PR DESCRIPTION
**Pull request by nathan818fr**
Currently, native-cipher.so is compiled with libcrypto 1.0.0 (from OpenSSL 1.0.0).

The majority of new or upcoming linux distribution switches to OpenSSL 1.1 without support for version 1.0.0 (eg, Debian 9 support only 1.0.2 and 1.1).
So I think the support of both version 1.0.0 and 1.1 could be interesting.

This pull request makes sure that the `compile-native.sh` append the libcrypto version after the cipher library name (eg `native-cipher.so.1.0.0`).
Then `NativeCode.java` try to load the different versions attached to the jar (the list of possible versions is hardcoded to avoid having to search all versions inside the jar at runtime; to discuss).

### CODE REVIEW

**Comment by md-5** [comment]
I think I'd rather just static link it & zlib, I've got the code lying around for that and it works. Will look tomorrow.

**Comment by md-5** [comment]
OpenSSL is quite large and also has a license that would require other changes to BungeeCord.
I've pushed a statically linked version of the native compression, and will push a static linked version of the cipher using mbed TLS tomorrow.

**Comment by nathan818fr** [comment]
You should also push the updated compile script.

mbed seem a good alternative for the cipher !

**Comment by md-5** [comment]
Closing out as we now use mbedTLS

**Pull request closed without merging**
