### PR TITLE
Checking username of LoginRequest

### PR DESCRIPTION
**Pull request by Outfluencer**
I cleaned up the code and use it for checking chat messages to. The old pr is #3185
and i moved the char to unicode to the util class

### CODE REVIEW

**Comment by md-5** [comment]
What validation does the Mojang server do?

**Comment by Outfluencer** [comment]
Mojang server validate only the name change and you only can user alphanumeric chars and _

**Comment by Outfluencer** [comment]
There is no name with other chars if there was mojang had removed them

**Comment by md-5** [comment]
I mean in offline mode

**Comment by md-5** [comment]
Or online mode for that matter, I don't see any validation?

**Comment by Outfluencer** [comment]
I added it for the reason that the chars are illegal  in the chat to and you could send connections with these name if a Player would have these names you could not ban them

**Pull request closed without merging**
