### PR TITLE
squid:S00118 - Abstract class names should comply with a naming conve…

### PR DESCRIPTION
**Pull request by m-ezzat**
This pull request is focused on resolving occurrences of Sonar rule squid:S00118 - Abstract class names should comply with a naming convention
You can find more information about the issue here:
https://dev.eclipse.org/sonar/coding_rules#q=squid:S00118
Please let me know if you have any questions.
M-Ezzat

### CODE REVIEW

**Comment by Paulomart** [comment]
Sure, this will totally not break 100% of all plugins.

**Comment by m-ezzat** [comment]
so, why didn't you merged it :)

**Comment by Black-Hole** [comment]
Rule number one tops it: You can't change names of public classes in an API.

**Comment by Janmm14** [comment]
:-1:

**Comment by kamcio96** [comment]
:-1: 
@m-ezzat your's PR are pointless...

**Comment by Janmm14** [comment]
md-5 stated in another pr that he has permission to create these semi-automated pull requests.

**Comment by md-5** [comment]
Thanks, but no thanks.

**Pull request closed without merging**
