### PR TITLE
Support uuid in config.yml

### PR DESCRIPTION
**Pull request by kamcio96**
Simple :)

### CODE REVIEW

**Comment by johnnywoof** [comment]
@kamcio96 Does it have backwards compatibility support?

**Comment by kamcio96** [comment]
Ofc :smiley:

**Comment by kamcio96** [comment]
could you merge it?

**Comment by johnnywoof** [comment]
Me? No. I believe only @md-5 and @thinkofdeath can.

**Comment by kamcio96** [comment]
@md_5 ?

**Comment by Janmm14** [comment]
@md-5 @thinkofdeath

**Comment by Janmm14** [comment]
@md-5

**Comment by md-5** [comment]
Added.

**Pull request closed without merging**
