### PR TITLE
Clear the address cache entry when a connection fails

### PR DESCRIPTION
**Pull request by thinkofdeath**
Should help solve the issues caused by mojang swapping the ip address of
the session server.

### CODE REVIEW

**Comment by md-5** [comment]
Seems sane, although there is still the internal JDK cache to worry about.
Will be nicer when Netty 4.1.0 releases and we get their DNS resolver.

**Comment by Paulomart** [comment]
Will this not cause a lookup spam when mojang is offline?

**Comment by kamcio96** [comment]
+1

**Comment by kamcio96** [comment]
@md-5 Can you add this PR as temporary solution?

**Comment by Janmm14** [comment]
@kamcio96 you could have a custom build

**Pull request closed without merging**
