### PR TITLE
Revert "Throw exception when ServerConnectEvent is handled badly"

### PR DESCRIPTION
**Pull request by kamcio96**
It's really unnecessary.

### CODE REVIEW

**Comment by md-5** [comment]
No its not, plugins put BungeeCord in a bad state and cause bugs which then get blamed on us.
You can't just leave a player in limbo

**Comment by kamcio96** [comment]
Ofc I can. I will call `connect` or `disconnect` few seconds later.

**Comment by md-5** [comment]
You "will" - bungee doesn't know this.
It's bad API to allow anything to set the proxy an an inconsistent state.

**Comment by kamcio96** [comment]
okey. Soo, AsyncEvent will be good?

**Pull request closed without merging**
