### PR TITLE
Fixed unicode characters in files

### PR DESCRIPTION
**Pull request by kamcio96**

### CODE REVIEW

**Comment by nathan818fr** [comment]
:+1: 
Really useful for non-english servers.

**Comment by md-5** [comment]
Ignoring all the stylistic issues, what is the actual issue. Can you please provide a unit test?

**Comment by kamcio96** [comment]
I can't make test (source code is encoded as UTF8), but try with eg "»" char

**Comment by md-5** [comment]
Works fine. This is why a test is needed.
tmecxii

**Comment by md-5** [comment]
This can only occur if that encoding of the file is different to the encoding of the server.
The solutions are as follows:
* Save the file with the correct encoding
* Switch the server to the correct encoding
* Force UTF-8 with -Dfile.encoding=UTF-8

Blindly treating all encodings as UTF-8 isn't the best idea.

**Comment by kamcio96** [comment]
Hmmm, I used UTF-8 in editor.

Did you try load, save file, and load again?

**Comment by md-5** [comment]
Then you must be in a non UTF-8 locale. If on Linux check the locale command.

**Comment by kamcio96** [comment]
right, I had ```POSIX```

**Comment by md-5** [comment]
Right, then you should save your file with ISO-8859-1 (Latin-1) I believe. This is user error.

**Pull request closed without merging**
