### PR TITLE
More time?

### PR DESCRIPTION
**Pull request by kamcio96**

### CODE REVIEW

**Comment by minecrafter** [comment]
No, all that's needed is to make a dummy commit to bump the build version.

**Comment by kamcio96** [comment]
Yes, but now this project has smaller activity. And it propably won't change :)

**Comment by Paulomart** [comment]
Just Start with -dIReallyKnowWhatIAmDoingISwear=true

**Comment by kamcio96** [comment]
I know, "=true" isn't required

**Comment by Paulomart** [comment]
Oh well, it works

**Comment by md-5** [comment]
We'll find some code to update :p

**Pull request closed without merging**
