### PR TITLE
Abstract method refactor

### PR DESCRIPTION
**Pull request by Robbie-1**
Original abstract method name: 
sendMessage(BaseComponent... message);

Proposed abstract method name:
sendMessages(Basecomponent... messages);

### CODE REVIEW

**Comment by yawkat** [comment]
This would be a breaking change. The current name is also descriptive since it is just one message.

**Comment by iKeirNez** [comment]
This is breaking and you also didn't update the implementation -_-

**Comment by Janmm14** [comment]
A message can consist of multiple BaseComponents. Multiple BaseComponents do not force a new line after each BaseComponent. So actually its correctly named.

**Comment by nikosgram13** [comment]
Does not recommended to change the method name.

**Pull request closed without merging**
