### PR TITLE
Avoid disconnecting player after lost connection

### PR DESCRIPTION
**Pull request by kamcio96**

### CODE REVIEW

**Comment by md-5** [comment]
Um what? The client is already disconnected by the time we reach here

**Comment by kamcio96** [comment]
Player lost connection to proxy, then proxy disconnect from server:
https://github.com/kamcio96/BungeeCord/blob/master/proxy/src/main/java/net/md_5/bungee/connection/UpstreamBridge.java#L82
After disconnect proxy kick player, what does not make sense.

**Comment by Janmm14** [comment]
If bungee does not disconnect the player from the server, the connection will likely timeout or staying idle unneccessary.
Also there is no problem needed to solve.

**Comment by kamcio96** [comment]
Bungee disconnect player with isn't anymore on proxy. It is wrong usage of netty.

**Comment by Janmm14** [comment]
But we need to close connection to server if player is disconnected.

Also if you set the server obsolete, I think every client connected to that server is going to time out.

**Comment by kamcio96** [comment]
@Janmm14 http://scr.hu/1s1h/04erc What that mean?

1. Player disconnect from proxy.
2. Kick player.
3. Proxy disconnect from server.

We shouldn't kick player!!!

**Comment by kamcio96** [comment]
Any changes? 
Now I found, bungee will call server.disconnect and close twice.

**Comment by kamcio96** [comment]
@md-5 ?

**Comment by Black-Hole** [comment]
There is a race condition where the player is disconnecting while the connection the the Spigot server is established.
This leads to an closed player connection while the server connection is still open. The player apears online on the Spigot server. The BungeeCord console is spammed with netty errors.
If the player tries to reconnect he's told that he could not be connected to any server. If you kick the player on the Spigot server he could connect again and the spamming of the BungeeCord console stops.

The reproduce connect to the server and try pressing "Cancel" at various delays.


BungeeCord log:
18:42:02 [FINE] [(IP address)] <-> InitialHandler has connected
18:42:02 [INFO] [BungeePerms] Login by BlackHole (4ce5450c-cb63-4337-b4cb-fa95761d4bef)
18:42:02 [INFO] [BlackHole] <-> ServerConnector <-> [main] has connected
18:42:02 [INFO] [BlackHole] -> UpstreamBridge has disconnected
18:42:02 [SEVERE] Jan 11, 2016 6:42:02 PM io.netty.channel.DefaultChannelPipeline$TailContext exceptionCaught
WARNING: An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.nio.channels.ClosedChannelException
...
18:42:32 [SEVERE] Jan 11, 2016 6:42:32 PM io.netty.channel.DefaultChannelPipeline$TailContext exceptionCaught
WARNING: An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.nio.channels.ClosedChannelException


Spigot log:
[18:42:02] [Thread-807/INFO]: UUID of player BlackHole is 4ce5450c-cb63-4337-b4cb-fa95761d4bef
[18:42:02] [Server thread/INFO]: [BungeePerms] Login by BlackHole (4ce5450c-cb63-4337-b4cb-fa95761d4bef)
[18:42:02] [Server thread/INFO]: BlackHole[(IP address)] logged in with entity id 4705 at ([main]-133.97357349791477, 64.0, 91.95724148899262)
[18:42:32] [Server thread/INFO]: BlackHole lost connection: Kicked by an operator.

**Comment by kamcio96** [comment]
@Black-Hole that error is with or without my patch?

**Comment by Black-Hole** [comment]
After applying both of your patches, unmodified.

**Comment by kamcio96** [comment]
Hmm, I don't know why there is that error.

Could you debug raw BungeeCord but with addListener(ChanelFutureListener.FIRE_EXCEPTION_ON_FALITURE) on sending packet?

It could be bungee bug, but it isn't show.

**Comment by Black-Hole** [comment]
I updated my BungeeCord build using your patches from https://github.com/SpigotMC/BungeeCord/pull/1706
The patch https://github.com/kamcio96/BungeeCord/commit/9ab2a0e8b6bd6fe531f82b98751f529407629168 contains your recommended changes. It doesn't change anything on the output.

Without your patches there is no exception spamming in the console, but the behaviour is the same. So it's a BungeeCord issue. I will open a ticket for it, so maybe someone will find a way to fix it. :)

**Comment by kamcio96** [comment]
@Black-Hole 
Propably https://github.com/SpigotMC/BungeeCord/blob/master/proxy/src/main/java/net/md_5/bungee/ServerConnector.java#L234 that part of code should be moved to line 183 or before. Could you test it? :smiley_cat:

**Comment by Black-Hole** [comment]
I tested it, but it didn't help. I think the error happens a little later, but even if I put it just before the throw statement it didn't change anything.
I'm lacking the deeper understanding of the packet sequence while a player logs in, so I don't know what happens "after" the throw statement. All I know is that sometimes later a proper disconnect handling is set up. The ServerSwitchEvent is the last event called by BungeeCord after a player logs in.

**Comment by kamcio96** [comment]
I don't know how reproduce that error
Could you try? 
```
if(!ch.isOpen()) Thread.dumpStack();
```
In ChannelWrapper::write method

**Comment by Black-Hole** [comment]
Thanks. The debugging was very helpful. The problem is:
UserConnection.isActive() checks if the channel is closed, but it's checking the ChannelWrapper.isClosed(). The field closed is declared volatile, so it shouldn't be a concurrence problem.
Any ideas how the ChannelWrapper could be notified if the channel is closed remotely?

**Comment by Black-Hole** [comment]
Here's a quick fix: https://gist.github.com/Black-Hole/dd5aee15edbd7b111c12

**Comment by kamcio96** [comment]
```
    public boolean isClosed() {
        return closed || !ch.isActive();
    }
```
hmm?

**Comment by kamcio96** [comment]
Included in https://github.com/SpigotMC/BungeeCord/pull/1874

**Pull request closed without merging**
