### PR TITLE
Add ability to disable Metrics

### PR DESCRIPTION
**Pull request by Outfluencer**
Some servers may don't want that data is collected by spigotmc we should provide a possibility to disable it

### CODE REVIEW

**Comment by Janmm14** [comment]
Well currently no data is collected anyway, as mcstats is offline since a couple years.

**Comment by Outfluencer** [comment]
So we could disable it by default and enable it again if mcstats would be online again

**Comment by LewUwU** [comment]
> Well currently no data is collected anyway, as mcstats is offline since a couple years.

Then, the metrics code can be deleted so we save a thread

**Comment by Janmm14** [comment]
> 
> 
> > Well currently no data is collected anyway, as mcstats is offline since a couple years.
> 
> Then, the metrics code can be deleted so we save a thread

Not executing the code, like its its done in this PR if metrics are disabled, it is enough to not have the thread. There is no need to delete the code.

**Pull request closed without merging**
