### PR TITLE
Remove unused enum in ServerConnector

### PR DESCRIPTION
**Pull request by Outfluencer**
also exceptions should be red

### CODE REVIEW

**Comment by Janmm14** [comment]
The unused enum field doesn't harm, but its removal could maybe harm some plugins which go bejond api.

**Comment by Outfluencer** [comment]
The enum is not api its private use only and the field doesnt have a getter also the enum is private and not accessable via any api

**Comment by caoli5288** [comment]
What does this commit fix or improve?

**Comment by Outfluencer** [comment]
It fixes the syntax of an disconnect message and removes an unused state for more clean and understandable code

**Pull request merged**
