### PR TITLE
Add isOnline() method

### PR DESCRIPTION
**Pull request by kamcio96**

### CODE REVIEW

**Comment by md-5** [comment]
Use case?

**Comment by kamcio96** [comment]
I have stored ProxiedPlayer eg in task, and checking isOnline() is faster than proxy.getPlayer() != null

**Comment by minecrafter** [comment]
Out of convenience (IDE auto-complete) or micro-optimization?

I'm neutral on this, I see where it can be useful though.

**Comment by md-5** [comment]
@kamcio96 ideally you should be removing them from tasks onDisconnect.
Any reason you can't do that?

**Comment by kamcio96** [comment]
Yes, I can do it with event.
But that method is easier :smile:

**Comment by ItsHarry** [comment]
This would be useful if say we run a very slow query to fetch data for a Player, so we can check whether the player is still online after the query has completed.

**Comment by md-5** [comment]
Expanded to Connection and renamed to isConnected.

Thanks

**Pull request closed without merging**
