### PR TITLE
support for snapshot 24w03a (1.20.5)

### PR DESCRIPTION
**Pull request by Outfluencer**
if you spot bugs please report

### CODE REVIEW

**Comment by Outfluencer** [comment]
i repackaged the packets as its not very nice to have that much packets flat

**Comment by Outfluencer** [comment]
i hope i can help you a bit out with this pr

**Comment by md-5** [comment]
> i repackaged the packets as its not very nice to have that much packets flat

Makes the PR extremely difficult to review. Please only include the changes necessary for snapshot support

**Comment by Outfluencer** [comment]
okay i will revert the renaming and create a new pr

**Comment by md-5** [comment]
Thanks

**Comment by Outfluencer** [comment]
look at #3602

**Comment by Janmm14** [comment]
As packets are part of api, renaming could break bunch of plugins using unsafe api

**Pull request closed without merging**
