### PR TITLE
Handle posix signals SIGTERM, SIGINT, & SIGHUP gracefully

### PR DESCRIPTION
**Pull request by coderobe**
These signals are used to signal the intent to quit a program.
This PR handles the signals using Java's shutdown hook mechanism
and triggers a clean shutdown as if `end` has been called.

### CODE REVIEW

**Comment by AixMC** [comment]
need this asap

**Comment by md-5** [comment]
Your comment literally does not help.
It hasn't been a feature for 5 years, it can wait a little longer. I've been away and then rather sick.

As hinted at one IRC I think the code here could be simplified greatly, particularly due to the ensued threads.

stop itself being threaded was essentially a kludge for /end in game t

**Comment by coderobe** [comment]
I suppose we could get rid of the whole ShutdownThread approach i adopted from the existing code and rather rely on the shutdown hook exclusively, having /end & co simply start a system exit.

What do you think?

**Comment by md-5** [comment]
Yeah I guess that works too as long as the other threads stay running long enough to make in game kick messages etc work

**Comment by coderobe** [comment]
I'll try that approach and clean up the other stuff in a bit then.

**Comment by md-5** [comment]
Handled in #2770, thanks though

**Pull request closed without merging**
