### PR TITLE
make ip command output clickable too copy ip

### PR DESCRIPTION
**Pull request by Outfluencer**

### CODE REVIEW

**Comment by Outfluencer** [comment]
i think its a very usefull feature if you need to do something with an ip of a user really quik :)

**Comment by md-5** [comment]
ComponentBuilder?

**Comment by Outfluencer** [comment]
Yes.

**Comment by md-5** [comment]
How come you're copying a different address to the one displayed?

**Comment by Outfluencer** [comment]
I never need the / or the port of the connection thats why I prefer only to copy the ip address

**Comment by Janmm14** [comment]
Incorrect usage of ComponentBuilder. A message using legacy color codes shall not be a direct input of ComponentBuilder or TextComponent. A proper conversion is needed.

**Comment by Outfluencer** [comment]
thank you Janmm14

**Pull request closed without merging**
