### PR TITLE
Move the compiler configuration to properties

### PR DESCRIPTION
**Pull request by sha-2**
Move the maven-compiler-plugin configuration to properties.

### CODE REVIEW

**Comment by md-5** [comment]
Reasoning?

**Comment by sha-2** [comment]
At the moment the maven-compiler-plugin will be downloaded twice. Once in version 3.1 for all modules expect these two ones. They use 2.5.1

**Comment by sha-2** [comment]
@md-5 I moved the things above the build timestamp.

**Comment by md-5** [comment]
Thanks

**Pull request closed without merging**
