### PR TITLE
Update messages with quote marks

### PR DESCRIPTION
**Pull request by ItsRenderman**
Change messages with single quotes to use its unicode equivalent [U+2019](https://unicode-table.com/en/2019/)

### CODE REVIEW

**Comment by md-5** [comment]
Why?

**Comment by ItsRenderman** [comment]
Prevent text editors believing the rest of the properties file is meant to be a string

**Comment by md-5** [comment]
Sounds like a bug in your text editor

**Comment by MrIvanPlays** [comment]
iirc its happening in ides such as intellij
so the problem is not the editor

**Comment by Janmm14** [comment]
> iirc its happening in ides such as intellij so the problem is not the editor

The problem must be the editor, as the current thing is a legitimate way of escaping the `'` char.

**Pull request closed without merging**
