### PR TITLE
Support vanilla on premium bungee

### PR DESCRIPTION
**Pull request by Outfluencer**
Set offline uuid in the LoginSuccess packet if online-mode=true and ipforward=false (this means we want to support vanilla)
Also dont change the offline uuids received from the server to online uuids otherwise the player is not able to chat as he can't verify the chatmessages

Closes #3604

### CODE REVIEW

**Comment by Outfluencer** [comment]
the client now receives every player as premium player but with an offline uuid, skins and capes are still visible

**Comment by md-5** [comment]
Thanks, this is what I had in mind.

EntityMap_1_16_2 looks OK already to me, but would be grateful for you to confirm?

**Comment by Outfluencer** [comment]
I think we could just check for vanilla and return if so as we dont want the client to receive the online uuid.
As i understand we are rewriting an offline uuid to an online uuid, but in vanilla we just want to keep the offline uuid, while i was testing with an 1.20.4 client i saw no exception in the client or issues in generell, but maybe this should be changed

**Comment by Outfluencer** [comment]
found out this is importet for old versions like 1.8.8 otherwise players are invisible

**Comment by Outfluencer** [comment]
now we don't replace offline uuid to online uuid if onlinemod and !ip-forward

**Comment by Outfluencer** [comment]
i think a getNetworkingId would be a good idea instead of checking for online mod and ip forward everytime
also changing this values in the config and reloading bungeecord woulod break everythin now, with a networking uuid this would also apply for new players that are joining so not everything would be broken

**Comment by Outfluencer** [comment]
not tested for now, but i think i'll do it like that

https://github.com/Outfluencer/BungeeCord/commit/162bc1a41bacc9a30ca2e7d37d9cdfba060a6e38

**Pull request closed without merging**
