### PR TITLE
Added string len checks for isValidName in AllowedCharacters

### PR DESCRIPTION
**Pull request by Outfluencer**
closes https://github.com/SpigotMC/BungeeCord/pull/3262

### CODE REVIEW

**Comment by md-5** [comment]
Does vanilla have a limit?

**Comment by md-5** [comment]
If the protocol has a limit then what is the point of this

**Comment by Outfluencer** [comment]
As it is a util class, i thought we should not expect the string to be in protocol limit

**Comment by Outfluencer** [comment]
And a string of more than 16 or less 1 is in fact not a valid name

**Comment by md-5** [comment]
It's not an API util though. I suppose the empty check is something

**Pull request merged**
