### PR TITLE
support vanilla in online mode with new chat signings

### PR DESCRIPTION
**Pull request by Outfluencer**

### CODE REVIEW

**Comment by Outfluencer** [comment]
technicly bungeecord uses offline for everything now if ipForward is disabled

**Comment by md-5** [comment]
Any chance you can see if you can reproduce #3606 and whether this fixes it?

Please and thanks

**Comment by md-5** [comment]
Thanks, looks good subject to question above. Appreciated

**Comment by Outfluencer** [comment]
> Any chance you can see if you can reproduce #3606 and whether this fixes it?
> 
> Please and thanks

i'll take a look

**Comment by Outfluencer** [comment]
> Any chance you can see if you can reproduce #3606 and whether this fixes it?
> 
> Please and thanks

Can reproduce, by dropping ChatSession packet

**Review by md-5 — APPROVED** [review]

**Comment by md-5** [comment]
Sorry I thought about this more and it is a bit of a change in that now the bungee API methods will also use offline UUIDs despite being only mode.

I need to investigate further whether in fact we can just rewrite the entity / other relevant packets (this is what used to be done)

**Comment by Outfluencer** [comment]
> Sorry I thought about this more and it is a bit of a change in that now the bungee API methods will also use offline UUIDs despite being only mode.
> 
> I need to investigate further whether in fact we can just rewrite the entity / other relevant packets (this is what used to be done)

yes a also thoght that this would maybe be an issue

**Comment by Outfluencer** [comment]
> Sorry I thought about this more and it is a bit of a change in that now the bungee API methods will also use offline UUIDs despite being only mode.
> 
> I need to investigate further whether in fact we can just rewrite the entity / other relevant packets (this is what used to be done)

done
i will make pr

**Comment by md-5** [comment]
Was there ever any progress with this, or still with me?

**Comment by Outfluencer** [comment]
> Was there ever any progress with this, or still with me?

i think i fogot to make the new pr i will look it up now

**Comment by Outfluencer** [comment]
done in #3650

**Pull request closed without merging**
