### PR TITLE
Add system property to enable throttle again

### PR DESCRIPTION
**Pull request by yawkat**

### CODE REVIEW

**Comment by md-5** [comment]
If we just make sure unthrottle is called after pings we can "fix" it.

**Comment by Janmm14** [comment]
Status on this?

**Comment by Janmm14** [comment]
I just decided to fix this issue myself, if anyone is intereseted they can look here: https://github.com/minotopiame/BungeeCord/commit/4fbbe99f804855a64747bab20aa2d4aa54591b74 or https://github.com/minotopiame/BungeeCordPatcher/commit/ab3442bc930192a59a6528129b05e14773a41082

**Comment by Janmm14** [comment]
Possibly superseded by #1825

**Comment by md-5** [comment]
https://github.com/SpigotMC/BungeeCord/commit/2e8ed1cfba4a23ee0c6aa723404482a9889eb040

**Pull request closed without merging**
