### PR TITLE
Implemented better configuration management (Issue #2601)

### PR DESCRIPTION
**Pull request by deeprobin**
* Added ConfigurationProviderNotRegisteredException
* Made the method ConfigurationProvider.getProvider accessable but
deprecated
* Added ConfigurationManager to manage configurations
* Added Getter for the ConfigurationManager in ProxyServer and
BungeeCord

(Issue #2601)

### CODE REVIEW

**Comment by md-5** [comment]
I still don't see the point. Why not just remove registration completely.

**Comment by DeepRobin** [comment]
Right, that would be a great idea.

**Comment by DeepRobin** [comment]
Or do you think I should delete the deprecated methods? Or how do you imagine it would be?

**Comment by md-5** [comment]
Same reasoning that I gave here; https://github.com/SpigotMC/BungeeCord/issues/2601
Just instantiate providers directly... With the current design the configuration manager doesn't actually do anything... A Class.forName(..).newInstance() call would have the same effect if you really wanted the user to be able to pick config format (but you would need extra code to change file extensions anyway..)

**Comment by DeepRobin** [comment]
> Same reasoning that I gave here; #2601
> Just instantiate providers directly... With the current design the configuration manager doesn't actually do anything... A Class.forName(..).newInstance() call would have the same effect if you really wanted the user to be able to pick config format (but you would need extra code to change file extensions anyway..)

Are there any suggestions for improvement or can you merge them?

**Comment by md-5** [comment]
What I'm saying is just pretend ConfigurationProvider doesn't exist.
Consider it an old quirk of the API.

I don't think any configuration aside from YamlConfiguration should ever worry about it.

**Comment by DeepRobin** [comment]
Okay can you merge it, or not?

**Comment by DeepRobin** [comment]
I've seen others also do a rewrite of the configuration system (Issue #2604 and Issue #2605). Maybe is this a better option. @md-5 Your choice!

**Pull request closed without merging**
