### PR TITLE
Set a more reasonable Recycler Capacity

### PR DESCRIPTION
**Pull request by aikar**
Default Netty Recycler capacity is 262k~, resulting in major memory consumption over long runtimes that will never free.

Potentially a netty leak, more info here:
https://github.com/netty/netty/issues/3166

after 2 weeks of uptime I started noticing more frequent old gen garbage collections, and realized it was near full and GC's were not bringing it down. Grabbed a heap dump and found the cause.

Class Name                                                                       | Shallow Heap | Retained Heap | Percentage
-----------------------------------------------------------------------------------------------------------------------------
java.lang.Thread @ 0x80086cc0  Netty IO Thread #0 Thread                         |          176 |   122,427,232 |      6.68%
|- java.lang.ThreadLocal$ThreadLocalMap @ 0x80183f18                             |           32 |   122,426,616 |      6.68%
|  '- java.lang.ThreadLocal$ThreadLocalMap$Entry[16] @ 0x80183f30                |          152 |   122,426,584 |      6.68%
|     |- java.lang.ThreadLocal$ThreadLocalMap$Entry @ 0x80183fa0                 |           56 |   122,425,472 |      6.68%
|     |  '- io.netty.util.internal.InternalThreadLocalMap @ 0x80183fc0           |          168 |   122,425,416 |      6.68%
|     |     |- java.lang.Object[32] @ 0x80184040                                 |          280 |   122,419,288 |      6.68%
|     |     |  |- io.netty.util.Recycler$Stack @ 0x801841b0                      |           72 |    67,831,360 |      3.70%
|     |     |  |  '- io.netty.util.Recycler$DefaultHandle[262144] @ 0xaaa9c2e0   |    2,097,176 |    67,831,288 |      3.70%
|     |     |  |     |- io.netty.buffer.PoolChunk @ 0xa944d278                   |          120 |       385,216 |      0.02%
|     |     |  |     |- io.netty.buffer.PoolChunk @ 0xa95281e0                   |          120 |       385,216 |      0.02%
|     |     |  |     |- io.netty.util.Recycler$DefaultHandle @ 0xa79c0ed8        |           40 |           248 |      0.00%
|     |     |  |     |  '- io.netty.buffer.PooledUnsafeDirectByteBuf @ 0xa79c0ef8|          128 |           208 |      0.00%
|     |     |  |     |- io.netty.util.Recycler$DefaultHandle @ 0xa79c0f50        |           40 |           248 |      0.00%
|     |     |  |     |  '- io.netty.buffer.PooledUnsafeDirectByteBuf @ 0xa79c0f70|          128 |           208 |      0.00%
|     |     |  |     |- io.netty.util.Recycler$DefaultHandle @ 0xa79c0fc8        |           40 |           248 |      0.00%
|     |     |  |     |- io.netty.util.Recycler$DefaultHandle @ 0xa79c1040        |           40 |           248 |      0.00%
|     |     |  |     |- io.netty.util.Recycler$DefaultHandle @ 0xa79c10b8        |           40 |           248 |      0.00%
|     |     |  |     |- io.netty.util.Recycler$DefaultHandle @ 0xa79c1130        |           40 |           248 |      0.00%
|     |     |  |     |- io.netty.util.Recycler$DefaultHandle @ 0xa79c11a8        |           40 |           248 |      0.00%
|     |     |  |     |- io.netty.util.Recycler$DefaultHandle @ 0xa79c1220        |           40 |           248 |      0.00%
|     |     |  |     |  '- io.netty.buffer.PooledUnsafeDirectByteBuf @ 0xa79c1240|          128 |           208 |      0.00%
|     |     |  |     |- io.netty.util.Recycler$DefaultHandle @ 0xa79c1298        |           40 |           248 |      0.00%
|     |     |  |     |- io.netty.util.Recycler$DefaultHandle @ 0xa79c1310        |           40 |           248 |      0.00%
|     |     |  |     |- io.netty.util.Recycler$DefaultHandle @ 0xa79c1388        |           40 |           248 |      0.00%
|     |     |  |     |  '- io.netty.buffer.PooledUnsafeDirectByteBuf @ 0xa79c13a8|          128 |           208 |      0.00%
|     |     |  |     |- io.netty.util.Recycler$DefaultHandle @ 0xa79c1400        |           40 |           248 |      0.00%
|     |     |  |     |- io.netty.util.Recycler$DefaultHandle @ 0xa79c1478        |           40 |           248 |      0.00%
|     |     |  |     |- io.netty.util.Recycler$DefaultHandle @ 0xa79c14f0        |           40 |           248 |      0.00%
|     |     |  |     |- io.netty.util.Recycler$DefaultHandle @ 0xa79c1568        |           40 |           248 |      0.00%
|     |     |  |     |- io.netty.util.Recycler$DefaultHandle @ 0xa79c15e0        |           40 |           248 |      0.00%
|     |     |  |     |  '- io.netty.buffer.PooledUnsafeDirectByteBuf @ 0xa79c1600|          128 |           208 |      0.00%
|     |     |  |     |- io.netty.util.Recycler$DefaultHandle @ 0xa79c1658        |           40 |           248 |      0.00%
|     |     |  |     |- io.netty.util.Recycler$DefaultHandle @ 0xa79c16d0        |           40 |           248 |      0.00%
|     |     |  |     |- io.netty.util.Recycler$DefaultHandle @ 0xa79c1748        |           40 |           248 |      0.00%
|     |     |  |     |  '- io.netty.buffer.PooledUnsafeDirectByteBuf @ 0xa79c1768|          128 |           208 |      0.00%
|     |     |  |     |- io.netty.util.Recycler$DefaultHandle @ 0xa79c17c0        |           40 |           248 |      0.00%
|     |     |  |     |  '- io.netty.buffer.PooledUnsafeDirectByteBuf @ 0xa79c17e0|          128 |           208 |      0.00%
|     |     |  |     |- io.netty.util.Recycler$DefaultHandle @ 0xa79c1838        |           40 |           248 |      0.00%
|     |     |  |     |- io.netty.util.Recycler$DefaultHandle @ 0xa79c18b0        |           40 |           248 |      0.00%
|     |     |  |     |- io.netty.util.Recycler$DefaultHandle @ 0xa79c1928        |           40 |           248 |      0.00%
|     |     |  |     '- Total: 25 of 262,146 entries                             |              |               |           
-----------------------------------------------------------------------------------------------------------------------------

### CODE REVIEW

**Comment by ninja-** [comment]
Your patch will make the situation worse and you can trust me on that. The recycler bug infinity doesn't apply and is long fixed. In your case the demand for entries went over 2 milion putting every next instance at GC pressure. You can take my netty patches at ninja/netty:4.1 just skip checkstyle and tests and that's a proper fix

**Comment by aikar** [comment]
How in the world would my demand have used that many entries? 
Even so, if theres a spike in demand, its much better to simply not return them to the pool.

It's never reasonable to be holding onto millions of buffers that will never realistically be used again.

Probally 2 sep issues here, unless there is a leak. Still, even with your fixes, should be a more sane cap on object pooling.

**Comment by ninja-** [comment]
There are few reasons for this for example
1. Small Packers lots of small Packers

**Comment by aikar** [comment]
"leak" no, but undesired amount of memory retention, yes.

This is essentially an unbounded object pool that does not compact.

Because 1 user abused the resources and spiked the allocation rate, those objects got thrown into the pool, never to be used again.

This is why you set reasonable caps on object pools. Ideally, you find your baseline allocation rate , add a little bit of room, and then anything over that can allocate new and not be returned to the pool (cause pools full)

This keeps allocation rate under control but also protects against unruly pools.

Right now, we have an unruly pool. Some kids able to attack the server, and force it to pool objects well beyond the user being kicked.

This is not desirable. I've bumped the limit to 10k 'to be safe', and if something really needs to go over that... it doesn't need to be returned to the pool. But this is still overkill.

My issue at hand has nothing to do with the rate, but more so the fact that unused objects are sitting in the pool.

**Comment by aikar** [comment]
just checked my current heapdump, and using 15k entries (non abused)

so, lets say 50k cap then should be sane for even larger servers.

**Comment by ninja-** [comment]
it's not a fix. you are making the problem worse by drastically increasing gc usage. if it has too much of these entries to gc it can even die.

**Comment by md-5** [comment]
Resolved

**Pull request closed without merging**
