### PR TITLE
Change channel closing

### PR DESCRIPTION
**Pull request by kamcio96**
Sometimes Bungee will close connection before the packet is sent to client.

### CODE REVIEW

**Comment by kamcio96** [comment]
@md-5 https://drive.google.com/file/d/0BzW42YF62IgxT1VRdXdHY2ZkTzA/view?usp=docslist_api

**Comment by DoctorDark** [comment]
Also closes #1604 I think

**Comment by kamcio96** [comment]
right

**Comment by kamcio96** [comment]
@md-5 Is something wrong in that PR?

**Comment by kamcio96** [comment]
https://github.com/SpigotMC/BungeeCord/pull/1706

**Pull request closed without merging**
