### PR TITLE
pmd:CommentDefaultAccessModifier -  Comment the default access modifier

### PR DESCRIPTION
**Pull request by m-ezzat**
This pull request is focused on resolving occurrences of Sonar rule pmd:CommentDefaultAccessModifier - Comment the default access modifier
You can find more information about the issue here:
https://dev.eclipse.org/sonar/coding_rules#q=pmd:CommentDefaultAccessModifier
Please let me know if you have any questions.
M-Ezzat

### CODE REVIEW

**Comment by Black-Hole** [comment]
I don't like this rule:
It's using a name with different meaning in java 8.
The default depends on the context, so it provided no clarity at all.

It only show others: Here I'm intentionally using the default access modifier.

**Comment by Janmm14** [comment]
I agree to @Black-Hole and also want to state that  partly tabs / spaces indentiation is messed up.
So :-1: for this.

**Comment by kamcio96** [comment]
still nothing
:-1:

**Comment by Paulomart** [comment]
I don't if it is just me but I think this is much harder to read then without comments

**Comment by Paulomart** [comment]
I also dont get the point of your prs. I think bungees code style is pretty good. Of cause you can always improve some things, but you break more then you fix.

**Comment by m-ezzat** [comment]
Thank you, guys :)

**Comment by md-5** [comment]
All,

Ezzat explicitly asked for permission to open these semi-automated PRs: http://files.md-5.net/s/7YeTTCmmzA.png

Please just let him do his thing and we will evaluate if the "rules" make sense to implement.

**Comment by Black-Hole** [comment]
Let's hope these tools will point out some real issues, too. ;)

**Comment by md-5** [comment]
Thanks, but no thanks.

**Pull request closed without merging**
