### PR TITLE
Add Connection's Information

### PR DESCRIPTION
**Pull request by nikosgram13**
I think it would be something nice to create a system that each connection (Server, Player, etc) has a directory where every plugin can add more additional information on it.

```java
connection.getInformation().set( "key", "test" );
connection.getInformation().getString( "key" ); //return test
```

### CODE REVIEW

**Comment by minecrafter** [comment]
Excessive reformatting for a feature that I feel has dubious purpose.

**Comment by md-5** [comment]
I don't see the need for such a loosely defined API.
If plugins need access to data they can expose their own API

**Comment by iKeirNez** [comment]
So this is like the Bukkit metadata api?

**Comment by nikosgram13** [comment]
Yeah.

**Pull request closed without merging**
