### PR TITLE
Don't lock connections for offline uuid lookup when given uuid is not offline mode

### PR DESCRIPTION
**Pull request by Janmm14**
All offline mode uuids are version 3, EntityMap might call it with online-mode uuid tho.

Cherry-picked from #3240

### CODE REVIEW

**Comment by md-5** [comment]
This needs a safety check on connectionsByOfflineUUID.put to ensure it really is the case

**Comment by Outfluencer** [comment]
How is it possible that this is not the case?

**Comment by Janmm14** [comment]
> How is it possible that this is not the case?

It is not possible in bungeecord code right now. I added the check anyway to make sure theres no weird plugin doing weird stuff.

**Comment by Outfluencer** [comment]
Okay great

**Pull request merged**
