### PR TITLE
Avoid coping buffer

### PR DESCRIPTION
**Pull request by kamcio96**
It really needs test.

Changes in netty class:
- add comment before ReferenceCountUtil.release(cast);

### CODE REVIEW

**Comment by yawkat** [comment]
Just use retain

**Comment by kamcio96** [comment]
How you want use retain method?

**Comment by md-5** [comment]
It's a bit more complicated than this, there are lots of reference issues with Bungee that need addressing. The // todo indicates that more correctly that buffer should be a slice.
Also if you have to import classes from Netty with slight modifications then it probably isn't the correct way to be doing this.

**Comment by kamcio96** [comment]
I'm still testing that solution and I don't have any problems ;)

**Pull request closed without merging**
