### PR TITLE
Remove exception-throwing anti-pattern and netty buffer unexpected behavior fix.

### PR DESCRIPTION
**Pull request by Master-chan**
* Replace throwing CancelSendSignal to returning boolean value to tell BossHandler that packet don't need sending.

* Fix platform and version depended netty behavior with ByteBufAllocator.DEFAULT.heapBuffer()

### CODE REVIEW

**Comment by minecrafter** [comment]
:+1:

**Comment by md-5** [comment]
Why?

**Comment by Master-chan** [comment]
Why what

**Comment by minecrafter** [comment]
I believe the intent is to make the behavior more clear as to what should happen. Throwing an exception to cancel sending the packet can be confusing.

**Comment by Master-chan** [comment]
Throwing exception to cancel sending is not confusing - it is bad programming practice.

**Comment by md-5** [comment]
According to whom? Is there a specific technical justification? It's not exactly uncommon: https://github.com/netty/netty/blob/4.1/common/src/main/java/io/netty/util/Signal.java

**Comment by Master-chan** [comment]
According to Oracle docs:
https://docs.oracle.com/javase/7/docs/api/java/lang/Error.html

**Comment by kamcio96** [comment]
Wait, I'm not sure about it.

Maybe something like
```
packet.setCancelled(true)
```

**Comment by Janmm14** [comment]
```packet.setCancelled( true )``` seems to be a nice suggestion to stop throwing exceptions.

**Comment by Master-chan** [comment]
Any suggestions on current realization?
I understand that this may be different from @md-5's point of view but I still think that throwing exceptions and error for anything other than exceptional situations and errors isn't good coding practice, and canceling packet sending isn't exceptional situation in BungeeCord.

**Pull request closed without merging**
