### PR TITLE
don't close health check directly

### LINKED ISSUE #3689: HAProxy layer 7 health-check not possible anymore
### Bungeecord version

52ab21b1ffcde905bad2a65e98d82424b72826c4

### Server version

any

### Client version

any

### Bungeecord plugins

any

### The bug

So this commit broke the HAProxy Layer 7 check:
https://github.com/SpigotMC/BungeeCord/commit/6e1751733f6b3dafe824dcd7f00d5ed86572ba37

Before  this commit, we could use a legacy proxy ping to make sure a Bungee instance is up & healthy:
```
 check-send-proxy check
        option tcp-check
        tcp-check send-binary fe
        tcp-check expect binary ff
```

This no longer seems possible, as the proxy now closes the connection, resulting in HAProxy marking the server as offline.
image

### Log output (links)

none

### Checking

- [X] I am using BungeeCord and **not a fork**. Issues with forks should not be reported here.
- [X] I think this is **not** an issue with a bungeecord plugin.
- [ ] I have not read these checkboxes and therefore I just ticked them all.
- [X] This is not a question or plugin creation help request.

### PR DESCRIPTION
**Pull request by Outfluencer**
Fixes #3689
Just check if the connection is a health check if so don't log exceptions

### CODE REVIEW

**Comment by md-5** [comment]
So you're just leaving a connection dangling because it started with a health check header?

This does not seem right and would be a DDoS vector

**Comment by Outfluencer** [comment]
It can only be a health check if proxy protocol is enabled and if so, you should firewall the port,
so i see no ddos risk

**Comment by Outfluencer** [comment]
Also the behaviour is now the same as before, only exceptions are not printed for healthchecks

**Comment by md-5** [comment]
> Also the behaviour is now the same as before, only exceptions are not printed for healthchecks

Right, so surely now the bug https://github.com/SpigotMC/BungeeCord/commit/6e1751733f6b3dafe824dcd7f00d5ed86572ba37 was designed to fix is back?

**Comment by andreasdc** [comment]
> It can only be a health check if proxy protocol is enabled and if so, you should firewall the port, so i see no ddos risk

Everyone can send the health check if I'm not wrong.

**Comment by Outfluencer** [comment]
What do you mean? the problem is that if you send custom data and try to receive a custom response via haproxy it does not work with my old pr, now it does

**Comment by Outfluencer** [comment]
The bug is not back but we got this as problem with my change #3689

**Comment by Outfluencer** [comment]
> > It can only be a health check if proxy protocol is enabled and if so, you should firewall the port, so i see no ddos risk
> 
> 
> 
> Everyone can send the health check if I'm not wrong.

BungeeCord only decodes bytes to a health check if the HaProxyDecoder is in the pipe, that is only the case if proxy protocol is enabled, and if so you should firewall the port so only the right HAProxy can access it

**Comment by andreasdc** [comment]
-

> > > It can only be a health check if proxy protocol is enabled and if so, you should firewall the port, so i see no ddos risk
> > 
> > 
> > Everyone can send the health check if I'm not wrong.
> 
> BungeeCord only decodes bytes to a health check if the HaProxyDecoder is in the pipe, that is only the case if proxy protocol is enabled, and if so you should firewall the port so only the right HAProxy can access it

That's right, but I think everyone can use the proxy to send such packets, but I'm not sure.

**Comment by Outfluencer** [comment]
> -
> 
> 
> 
> > > > It can only be a health check if proxy protocol is enabled and if so, you should firewall the port, so i see no ddos risk
> 
> > > 
> 
> > > 
> 
> > > Everyone can send the health check if I'm not wrong.
> 
> > 
> 
> > BungeeCord only decodes bytes to a health check if the HaProxyDecoder is in the pipe, that is only the case if proxy protocol is enabled, and if so you should firewall the port so only the right HAProxy can access it
> 
> 
> 
> That's right, but I think everyone can use the proxy to send such packets, but I'm not sure.

?

**Comment by md-5** [comment]
> What do you mean? the problem is that if you send custom data and try to receive a custom response via haproxy it does not work with my old pr, now it does

This change reverts https://github.com/SpigotMC/BungeeCord/commit/6e1751733f6b3dafe824dcd7f00d5ed86572ba37 which fixed https://github.com/SpigotMC/BungeeCord/issues/3608

How is #3608 not reintroduced in cases where HAProxy doesn't try to send custom data?

**Comment by Outfluencer** [comment]
> > What do you mean? the problem is that if you send custom data and try to receive a custom response via haproxy it does not work with my old pr, now it does
> 
> 
> 
> This change reverts https://github.com/SpigotMC/BungeeCord/commit/6e1751733f6b3dafe824dcd7f00d5ed86572ba37 which fixed https://github.com/SpigotMC/BungeeCord/issues/3608
> 
> 
> 
> How is #3608 not reintroduced in cases where HAProxy doesn't try to send custom data?
> 
> 
> 
> Not printing an exception to the console after the connection is already closed will not affect HAProxy

Why will it not affect it? We just dont want to log the exception that is caused by the connection close of an health check.
Isnt this the solution for it?

**Comment by md-5** [comment]
I see, so #3608 is purely cosmetic

**Comment by Outfluencer** [comment]
> I see, so #3608 is purely cosmetic 

Yes

**Comment by andreasdc** [comment]
> Also the behaviour is now the same as before, only exceptions are not printed for healthchecks

How it's the same if channel is not being closed with the latest change?

**Comment by Outfluencer** [comment]
> > Also the behaviour is now the same as before, only exceptions are not printed for healthchecks
> 
> 
> 
> How it's the same if channel is not being closed with the latest change?

Because haProxy closes the connection by itself by default. I only closed the channel so we dont receive rst from the haProxy that causes the exception. Now we receive the rst und the exception is thrown but we dont print it for healthchecks. In both cases there are no exceptions spammed anymore

**Pull request merged**
