### PR TITLE
send offline uuid to client and server if ip-forward is disabled

### PR DESCRIPTION
**Pull request by Outfluencer**
old pr #3650

i think this pr is a much nicer solution

### CODE REVIEW

**Comment by Outfluencer** [comment]
btw how do i make my commits signed in intellij?

**Comment by Janmm14** [comment]
> btw how do i make my commits signed in intellij?

Settings -> Version Control -> Git
or search for "GPG" in Settings

**Comment by Outfluencer** [comment]
Yes worked fine for me

**Comment by md-5** [comment]
Thanks!

**Pull request closed without merging**
