### PR TITLE
Update YamlConfiguration.java

### PR DESCRIPTION
**Pull request by AxiImpact**

### CODE REVIEW

**Comment by xxyy** [comment]
Why

**Comment by shawlaf** [comment]
what even

**Comment by WolverinDEV** [comment]
whis changes are useless. You can understand the sense of the variables without your changes.

**Comment by Janmm14** [comment]
You just went into the file and renamed all `config` to `server`. This code won't even compile. Also the variable name change is useless, its still a configuration and no server.

@md-5 Please close this.

**Comment by i9hdkill** [comment]
No description provided and pretty much useless anyway.

**Pull request closed without merging**
