### PR TITLE
Fix negative packet ids error

### PR DESCRIPTION
**Pull request by KaiKikuchi**
Fixes https://github.com/SpigotMC/BungeeCord/issues/1437

### CODE REVIEW

**Comment by KaiKikuchi** [comment]
Works with Agrarian Skies 2 1.0.37a (CoFHCore-[1.7.10]3.0.2-262)

**Comment by md-5** [comment]
Are you saying some mod has negative IDs?

**Comment by KaiKikuchi** [comment]
Nope. Check this https://github.com/SpigotMC/BungeeCord/issues/1437

**Comment by md-5** [comment]
Rejected -> custom packets not supported.

**Pull request closed without merging**
