### PR TITLE
Add player positioning api

### PR DESCRIPTION
**Pull request by MrIvanPlays**

### CODE REVIEW

**Comment by Black-Hole** [comment]
This is very incomplete. It represents coodinates the client wishes to move to. There are many packets where the server sets the position of the entity and in newer versions the client have to reply the teleport id. And there are even more packets the clients could send, like https://wiki.vg/Protocol#Player_Position_And_Look_.28serverbound.29

Please also descripe the goals of your PR.

**Comment by MrIvanPlays** [comment]
> This is very incomplete. It represents coodinates the client wishes to move to. There are many packets where the server sets the position of the entity and in newer versions the client have to reply the teleport id. And there are even more packets the clients could send, like https://wiki.vg/Protocol#Player_Position_And_Look_.28serverbound.29
> 
> Please also descripe the goals of your PR.

OOF be4 i was looking at the clientbound. Gonna fix this asap

**Comment by MrIvanPlays** [comment]
Ok i got into a problem with this. There's no serverbound packet for 1.8 which is a RIP 1.8

**Comment by MrIvanPlays** [comment]
With some testing on 1.14 it looks like it works properly
[img

**Comment by ApocalypsjeNL** [comment]
Why would you want to know the player location if you can't really do anything with it at the proxy side

**Comment by Paulomart** [comment]
Also see #709.

**Comment by Janmm14** [comment]
Feel free to have it in your bungeecord fork, but adding a packet to decode which is sent 20 times per second per player just for the sake of plugins maybe making use of this is a big no-no from my site.
It'd hit performance hard.

**Comment by MrIvanPlays** [comment]
> Not even worth to say that simply ignoring version 1.8 without notice is another no go in my opinion.

Not ignoring it, just the packet that its currently using does not exist. In 1.8 the Player position and look packet is only clientbound, but here i use a serverbound one.


> Additionally adding setPosition to the api without a huuuuuugeeee warning is a no from me too. Easily breaks client-server synchronization, especially the downstreambridge handling. Anticheats might easily false-positive also.

I am gonna add warning.


> At least you didn't add an event.

What event for example?

**Comment by Janmm14** [comment]
> Not ignoring it, just the packet that its currently using does not exist. In 1.8 the Player position and look packet is only clientbound, but here i use a serverbound one.

In 1.8 the client sends its position too... similar like in 1.9+
1.8 protocol https://wiki.vg/index.php?title=Protocol&oldid=7368#Player
1.9 protocol https://wiki.vg/index.php?title=Protocol&oldid=7617#Player_Position

**Comment by MrIvanPlays** [comment]
> > Not ignoring it, just the packet that its currently using does not exist. In 1.8 the Player position and look packet is only clientbound, but here i use a serverbound one.
> 
> In 1.8 the client sends its position too... similar like in 1.9+
> 1.8 protocol https://wiki.vg/index.php?title=Protocol&oldid=7368#Player
> 1.9 protocol https://wiki.vg/index.php?title=Protocol&oldid=7617#Player_Position
> 
> Additionally you are only using the player position and look packet, but if the look doesn't change and only the position, the client sends another packet, similar to the client only changing its yaw/pitch and not moving.
> 
> -> you'll have to register 3 packets if you want this
> 
> **But I don't think md_5 will accept this PR**, see [#709 (comment)](https://github.com/SpigotMC/BungeeCord/pull/709#issuecomment-33886330)

Will try to make it with that 3 packets. Also this PR was made on 1.7 version, we're currently at 1.14 and 1.8 changes were made 5 years ago.

**Comment by MrIvanPlays** [comment]
Still wondering how i haven't seen the packet! There were no need for changing packets & stuff.

**Comment by Janmm14** [comment]
Other question: Is there any use case for this you have in mind?

**Comment by MrIvanPlays** [comment]
> Other question: Is there any use case for this you have in mind?

In the future i think to PR a playsound packet, but the time will say

**Comment by Paulomart** [comment]
Why even bother with this on proxy level. Just use a Bukkit plugin? If you still want to play a sound just use a PluginMessage that the proxy sends to your Bukkit Plugin.

**Comment by MrIvanPlays** [comment]
> Why even bother with this on proxy level. Just use a Bukkit plugin? If you still want to play a sound just use a PluginMessage that the proxy sends to your Bukkit Plugin.

Yeah ik, but won't it be cool to be on a proxy level? You won't play with the plugin messaging channel, and the bungee api will expand even more.

**Comment by Paulomart** [comment]
The proxy shouldn't bother with this:

- It's way to much packets to handle
- It will never work as good as on Bukkit level
- Bungee was not designed for this

**Comment by MrIvanPlays** [comment]
> * It will never work as good as on Bukkit level

Who said it should work as good as on Bukkit level? It should work, the other things are not important :P. It won't lag, as bungee already can handle a bunch of packet updating & so on, as i have tested it with player killing (respawn packet) and also logins.

**Comment by Janmm14** [comment]
In my opinion its cool to have the proxy working and doing somewhat minimal work for best performance results. Some convenient apis without huge performance impact can be added for sure.

This PR adds 40 shortliving objects per player per second, reflection calls to possible event listeners, likely stressing gc and cpu. Imagine 400 players on one proxy.

The alternative with involving bukkit is sending one packet to bukkit, not really impacting performance. And bukkit already deocdes all packets.

**Comment by MrIvanPlays** [comment]
Mr @md-5 can you tell me your opinion please?

**Comment by Tim203** [comment]
You can make your own BungeeCord packet handler and add those packets (there are multiple). This will impact performance for all the people who really don't need this. And Bungee is a lightweight proxy, and the move packets are the most spamming packets of them all. You then also need to listen for teleport packets and use basic logic to see if the user does not cheat. It is really to complex for a simple proxy

**Comment by MrIvanPlays** [comment]
> You can make your own BungeeCord packet handler and add those packets (there are multiple). This will impact performance for all the people who really don't need this. Bungee is a lightweight proxy, and the move packets are the most spamming packets of them all. When implementing this you also need to listen for teleport packets and use basic logic to see if the user does not cheat (because the client can trigger something on bungee without the client beeing legit there). It is really to complex and to heavy for a simple proxy and should therefore not be implemented in the main version.

I haven't heared about bungee sided anti cheats (also they can't be made on proxy level as there should be much more api than that provided). If we start talking about performance, bungee has tons shit which affects performance to downgrade and which can be removed. 

I knew it wont be accepted, because here you don't accept ANY performance affect OR api change, which affects performance to downgrade/upgrade. Closing this as md_shit don't reply.

**Comment by Tim203** [comment]
I think the BungeeCord community would love to hear your improvements to make it even more lightweight

**Comment by Janmm14** [comment]
Its open source software so you can simply maintain a fork with thos api present.
However performance is really an important factor in bungeecord.

**Comment by MrIvanPlays** [comment]
> Its open source software so you can simply maintain a fork with thos api present.
> However performance is really an important factor in bungeecord.

Velocity is better. I recommend everyone switching to Velocity. It does not have the shit bungee has.

**Comment by Tim203** [comment]
@MrIvanPlays because they accepted a pull request and not here? And plz explain the shit so the shit can be fixed x)

**Comment by Tim203** [comment]
And you can try to add the positioning api in Velocity. Maybe they can explain it better or maybe they will accept it

**Comment by MrIvanPlays** [comment]
> @MrIvanPlays because they accepted one of your pull requests and not here? And plz explain the shit so the shit can be fixed x)

Nope. The overall performance is about 90% better than the bungee one. 



> And you can try to add the positioning api in Velocity. Maybe they can explain it better or maybe they will accept it

DIY, I am not going to pr anymore on proxies. It looks like all of you hate me. When i appear somewhere, you are literally starting to blame over the thing i did.

**Comment by Tim203** [comment]
> Nope. The overall performance is about 90% better than the bungee one.
Don't know, never used it.
> It looks like all of you hate me. When i appear somewhere, you are literally starting to blame over the thing i did.
Never reacted to a pull request from Bungee. And I am defending something that really not needed and would impact performance bad. And Velocity accepted your pr from BossBar, so that's false

**Comment by Janmm14** [comment]
Ahahaha the hate starts when he is missing arguments as to why bungee should add a performance degrading feature in bungeecord.
When you already think that bungee has bad performance, why you pr at all

**Comment by Tim203** [comment]
🤷‍♀️😂

**Comment by MrIvanPlays** [comment]
> When you already think that bungee has bad performance, why you pr at all

Because I want improvements. But when md_5 does not accept anything and there are open pull requests since 2014 then you start thinking that "the developer does not care about the community at all and does things he thinks are good for the product" while many of the things "the developer thinks are good for the product" are not good. 

In a my fork which is not public i remove the ton shit bungee has while adding this specific pull request. Guess what: the performance got to Velocity level.

**Comment by Tim203** [comment]
>Guess what: the performance got to Velocity level
>Not with this pr 4 sure. But would still love to see your improvements.

**Comment by MrIvanPlays** [comment]
> > Guess what: the performance got to Velocity level
> 
> Not with this pr 4 sure. But would still love to see your improvements.

I am leaving md_5 found the trash that should be removed from bungee. And i am not going to pr it.

**Pull request closed without merging**
