### PR TITLE
Add "Not authenticated with Minecraft.net" message in the messages.properties

### PR DESCRIPTION
**Pull request by MisterFrans**
I'm French and if an offline player tries to connect on my network he doesn't understand why he can't connect.

### CODE REVIEW

**Comment by Paulomart** [comment]
This message is implement serverside, but never shown by the client. Instead vanilla shows an internal error message.

**Comment by MisterFrans** [comment]
The message is shown when a offline player tries to connect on a online mode proxy. It's not a server side message
jmsb0se7

**Comment by Paulomart** [comment]
Oh, what minecraft version are you using btw?

**Comment by MisterFrans** [comment]
The last version of bungeecord and Minecraft 1.8.8 to 1.11.2 in offline mode with MultiMC for simulate a cracked minecraft client

**Pull request merged**
