### PR TITLE
Possibly fix #2783

### LINKED ISSUE #2783: keepalive queue polling problem
See discussion here:
https://github.com/SpigotMC/BungeeCord/commit/eeb374798b10786bb87175796b55bed0275d56c7#commitcomment-37700213

We have to use peek() first to get the keepalive number to compare to, and only call poll if it fits.

Otherwise, as long as the queue never empties (happens when many keepalives are sent or connection has great latency), we are at least off by one keepalive until next server switch.

### PR DESCRIPTION
**Pull request by MrIvanPlays**
Waiting for a review & someone to test this.

### CODE REVIEW

**Comment by MrIvanPlays** [comment]
I've performed a test

My location: Plovdiv, Bulgaria
Proxy server location: Paris, France
Test server 1 location: Paris, France
Test server 2 location: localhosted by me (Plovdiv, Bulgaria)

Plugins: none
Spigot servers version: 1.15.2

Server names:
  - lobby is Test server 1
  - other is Test server 2

With these changes (some additional debugging added):

```07:21:09 [INFO] [/<ip hided>:50547] <-> InitialHandler has pinged
07:21:10 [INFO] [/<ip hided>:50548] <-> InitialHandler has connected
07:21:11 [INFO] Connecting MrIvanPlays to BungeeServerInfo(name=lobby, socketAddress=/<ip hided>:25623, restricted=false)
07:21:11 [INFO] [MrIvanPlays] <-> ServerConnector [lobby] has connected
07:21:26 [INFO] Received KeepAlive
07:21:26 [INFO] KeepAlive id: 281313511
07:21:26 [INFO] KeepAliveData != null, matched
07:21:26 [INFO] MrIvanPlays new ping is 36
07:21:41 [INFO] Received KeepAlive
07:21:41 [INFO] KeepAlive id: 281328511
07:21:41 [INFO] KeepAliveData != null, matched
07:21:41 [INFO] MrIvanPlays new ping is 36
07:21:56 [INFO] Received KeepAlive
07:21:56 [INFO] KeepAlive id: 281343511
07:21:56 [INFO] KeepAliveData != null, matched
07:21:56 [INFO] MrIvanPlays new ping is 36
07:22:11 [INFO] Received KeepAlive
07:22:11 [INFO] KeepAlive id: 281358511
07:22:11 [INFO] KeepAliveData != null, matched
07:22:11 [INFO] MrIvanPlays new ping is 36
07:22:26 [INFO] Received KeepAlive
07:22:26 [INFO] KeepAlive id: 281373560
07:22:26 [INFO] KeepAliveData != null, matched
07:22:26 [INFO] MrIvanPlays new ping is 35
07:22:30 [INFO] §cCommand not found
07:22:36 [INFO] MrIvanPlays executed command: /server other
07:22:36 [INFO] Connecting MrIvanPlays to BungeeServerInfo(name=other, socketAddress=/<ip hided>:1003, restricted=false)
07:22:36 [INFO] [MrIvanPlays] <-> ServerConnector [other] has connected
07:22:36 [INFO] [MrIvanPlays] <-> DownstreamBridge <-> [lobby] has disconnected
07:22:51 [INFO] Received KeepAlive
07:22:51 [INFO] KeepAlive id: 2079590
07:22:51 [INFO] KeepAliveData != null, matched
07:22:51 [INFO] MrIvanPlays new ping is 35
07:23:06 [INFO] Received KeepAlive
07:23:06 [INFO] KeepAlive id: 2094595
07:23:06 [INFO] KeepAliveData != null, matched
07:23:06 [INFO] MrIvanPlays new ping is 40
07:23:21 [INFO] Received KeepAlive
07:23:21 [INFO] KeepAlive id: 2109642
07:23:21 [INFO] KeepAliveData != null, matched
07:23:21 [INFO] MrIvanPlays new ping is 35```

Without these changes (some additional debugging added)

```07:33:44 [INFO] [/<ip hided>:50859] <-> InitialHandler has connected
07:33:45 [INFO] Connecting MrIvanPlays to BungeeServerInfo(name=other, socketAddress=/<ip hided>:1003, restricted=false)
07:33:45 [INFO] [MrIvanPlays] <-> ServerConnector [other] has connected
07:34:00 [INFO] Received KeepAlive
07:34:00 [INFO] KeepAlive id: 2748291
07:34:00 [INFO] KeepAliveData != null, matched
07:34:00 [INFO] MrIvanPlays new ping is 42
07:34:15 [INFO] Received KeepAlive
07:34:15 [INFO] KeepAlive id: 2763291
07:34:15 [INFO] KeepAliveData != null, matched
07:34:15 [INFO] MrIvanPlays new ping is 42
07:34:30 [INFO] Received KeepAlive
07:34:30 [INFO] KeepAlive id: 2778292
07:34:30 [INFO] KeepAliveData != null, matched
07:34:30 [INFO] MrIvanPlays new ping is 42
07:34:34 [INFO] MrIvanPlays executed command: /server lobby
07:34:34 [INFO] Connecting MrIvanPlays to BungeeServerInfo(name=lobby, socketAddress=/<ip hided>:25623, restricted=false)
07:34:34 [INFO] [MrIvanPlays] <-> ServerConnector [lobby] has connected
07:34:34 [INFO] [MrIvanPlays] <-> DownstreamBridge <-> [other] has disconnected
07:34:49 [INFO] Received KeepAlive
07:34:49 [INFO] KeepAlive id: 282116761
07:34:49 [INFO] KeepAliveData != null, matched
07:34:49 [INFO] MrIvanPlays new ping is 42
07:35:04 [INFO] Received KeepAlive
07:35:04 [INFO] KeepAlive id: 282131762
07:35:04 [INFO] KeepAliveData != null, matched
07:35:04 [INFO] MrIvanPlays new ping is 42
07:35:19 [INFO] Received KeepAlive
07:35:19 [INFO] KeepAlive id: 282146821
07:35:19 [INFO] KeepAliveData != null, matched
07:35:19 [INFO] MrIvanPlays new ping is 42
07:35:34 [INFO] Received KeepAlive
07:35:34 [INFO] KeepAlive id: 282161861
07:35:34 [INFO] KeepAliveData != null, matched
07:35:34 [INFO] MrIvanPlays new ping is 42
07:35:49 [INFO] Received KeepAlive
07:35:49 [INFO] KeepAlive id: 282176861
07:35:49 [INFO] KeepAliveData != null, matched
07:35:49 [INFO] MrIvanPlays new ping is 43
07:36:04 [INFO] Received KeepAlive
07:36:04 [INFO] KeepAlive id: 282191861
07:36:04 [INFO] KeepAliveData != null, matched
07:36:04 [INFO] MrIvanPlays new ping is 42
07:36:19 [INFO] Received KeepAlive
07:36:19 [INFO] KeepAlive id: 282206910
07:36:19 [INFO] KeepAliveData != null, matched
07:36:19 [INFO] MrIvanPlays new ping is 45
07:36:34 [INFO] Received KeepAlive
07:36:34 [INFO] KeepAlive id: 282221910
07:36:34 [INFO] KeepAliveData != null, matched
07:36:34 [INFO] MrIvanPlays new ping is 45
07:36:49 [INFO] Received KeepAlive
07:36:49 [INFO] KeepAlive id: 282236913
07:36:49 [INFO] KeepAliveData != null, matched
07:36:49 [INFO] MrIvanPlays new ping is 43
07:37:04 [INFO] Received KeepAlive
07:37:04 [INFO] KeepAlive id: 282251962
07:37:04 [INFO] KeepAliveData != null, matched
07:37:04 [INFO] MrIvanPlays new ping is 43
07:37:12 [INFO] MrIvanPlays executed command: /server other
07:37:12 [INFO] Connecting MrIvanPlays to BungeeServerInfo(name=other, socketAddress=/<ip hided>:1003, restricted=false)
07:37:12 [INFO] [MrIvanPlays] <-> ServerConnector [other] has connected
07:37:12 [INFO] [MrIvanPlays] <-> DownstreamBridge <-> [lobby] has disconnected
07:37:27 [INFO] Received KeepAlive
07:37:27 [INFO] KeepAlive id: 2955445
07:37:27 [INFO] KeepAliveData != null, matched
07:37:27 [INFO] MrIvanPlays new ping is 53
07:37:42 [INFO] Received KeepAlive
07:37:42 [INFO] KeepAlive id: 2970492
07:37:42 [INFO] KeepAliveData != null, matched
07:37:42 [INFO] MrIvanPlays new ping is 42
07:37:57 [INFO] Received KeepAlive
07:37:57 [INFO] KeepAlive id: 2985540
07:37:57 [INFO] KeepAliveData != null, matched
07:37:57 [INFO] MrIvanPlays new ping is 41
07:38:12 [INFO] Received KeepAlive
07:38:12 [INFO] KeepAlive id: 3000590
07:38:12 [INFO] KeepAliveData != null, matched
07:38:12 [INFO] MrIvanPlays new ping is 42```

There was also a debug for blocked KeepAlive, but it looks like in my tests it didn't occur. 
It looks like that these changes (somewhat) give a little bit more acurate information. I cannot reproduce huge ping spikes.

Additional testing required!

**Comment by md-5** [comment]
I don't understand what is your debugging supposed to show that indicates this fixes something?

**Comment by MrIvanPlays** [comment]
> I don't understand what is your debugging supposed to show that indicates this fixes something?

My debugging shows that the changes give even more acurate data. Also frees up memory (not much, but it does). And as I said, more testing is required.

**Comment by Janmm14** [comment]
@md-5 Did you understand the problem?

**Pull request closed without merging**
