### PR TITLE
Fixed NPE in PreLoginEvent

### PR DESCRIPTION
**Pull request by Outfluencer**
NPE is thrown if event is canceled and setCancelReason has not been called #2943

### CODE REVIEW

**Comment by md-5** [comment]
Bungee only uses getCancelReasonComponents so this fix can't possibly work

**Comment by Outfluencer** [comment]
I think this should do the job

**Comment by Mystiflow** [comment]
I think your solution wouldn't send the necessary kick packet which would affect plugins and packet handlers. I'd suggest something along the lines of...

```
static final String NULL_DISCONNECT = ComponentSerializer.toString( new TextComponent( "Disconnected" ) );
///
///
ch.delayedClose( new Kick( ( reason != null ) ? ComponentSerializer.toString( reason ) : NULL_DISCONNECT ) );
```

**Comment by Outfluencer** [comment]
Did it like you suggested, but should we check if a the arrays contains null?

**Comment by Mystiflow** [comment]
also could do the same thing here:
https://github.com/SpigotMC/BungeeCord/blob/master/proxy/src/main/java/net/md_5/bungee/connection/InitialHandler.java#L513

ServerKickEvent has a similar mechanism setKickReason|setCancelled but that's probably not relevant to the NPE here anyway

> Did it like you suggested, but should we check if the arrays contains null?

I think that would be more on the plugin author making dodgy components using unsupported methods, as opposed to not providing a cancel reason for a cancelled event

**Comment by Outfluencer** [comment]
The possible NPE in the LoginEvent should be fixed to

**Comment by Outfluencer** [comment]
there is no problem with the ServerKickEvent in both cases this event is fired there is no way the components can be null because the getKickReasonComponent method would return the message the player was kicked for

**Pull request closed without merging**
