### PR TITLE
Queue packets of Title api

### PR DESCRIPTION
**Pull request by Outfluencer**
if sending titles using the api in an PostLoginEvent

Example :

player.sendTitle(new BungeeTitle().title(new TextComponent("Hallo")));

this PR fixes this issue

image

### CODE REVIEW

**Comment by md-5** [comment]
Isn't sendPacketQueued safe for all versions?

**Comment by md-5** [comment]
Bump & cc @bob7l re their comment

**Comment by Outfluencer** [comment]
I was also thinking about it, yes it should be safe for all versions but its not needed for all

**Comment by md-5** [comment]
For consistency it should just be the one call

**Comment by Outfluencer** [comment]
Like this?

**Pull request merged**
