### PR TITLE
Put name into a variable

### PR DESCRIPTION
**Pull request by sinnlosername**
Put name into a variable because more customization :)

### CODE REVIEW

**Comment by minecrafter** [comment]
What is the point?

**Comment by sinnlosername** [comment]
Change name for serverping&co to eg. "You need version {version}". :p 
So a variable can be changed more easily as a void :3

**Comment by minecrafter** [comment]
There is still no use for this. If you genuinely wanted to fork BungeeCord, there's a lot of references to the name "BungeeCord" that abound throughout the source code.

**Comment by md-5** [comment]
@minecrafter no he is stating for the server list ping response.

He should be using the ServerPingEvent though.

**Comment by sinnlosername** [comment]
@md-5 
Bot how to know if the player has the correct version? :o

**Comment by Janmm14** [comment]
@sinnlosername What you wanted to change here does nothing related to server ping or login.

**Pull request closed without merging**
