### PR TITLE
Add methods for concisely resetting parts of a component to ComponentBuilder.

### PR DESCRIPTION
**Pull request by minecrafter**
This method adds `reset()`, `retain()`, and a new overload of `append()` that accepts the parts of the components to be retained to `ComponentBuilder`. This is useful to cut down on boilerplate and prevent incorrect usage of `ComponentBuilder`.

**Original description:**

This method is simple: it resets the current part to default settings, keeping only the current text. It therefore acts like the old ChatColor.RESET code.

This method can save several lines of code in certain complex usages of ComponentBuilder. A test is included to ensure that `reset()` properly works.

### CODE REVIEW

**Comment by PunKeel** [comment]
Linked issue: #1293

**Comment by tkausl** [comment]
I was looking for this, would've PR'd this myself if it wouldn't have PR'd yet. One thing i would appreciate: A method to just reset events, not colors.

**Comment by minecrafter** [comment]
On that topic, what kind of support is out there for a related `append(String, ComponentBuilder.TextKind)` method that does the same thing as this function but in a more condensed way?

**Comment by tkausl** [comment]
Yeah, that would be another way to go. There is no support for this yet, but someting like 
```
append("Hello", Inherit.ALL)
append("Hello", Inherit.FORMAT)
append("Hello", Inherit.NOTHING)
```
would be nice

**Comment by minecrafter** [comment]
I've added a parameter to `append()` now.

**Comment by JBou** [comment]
Really nice. That feature would be very useful!

**Comment by md-5** [comment]
Can you please quickly give a use case demonstration of this and an example where people may be using it incorrectly at the moment.

**Comment by JBou** [comment]
If I use the following code, the whole line has a click event, but I only want that the Player name is clickable. So I think that the .append() method should reset the following part to default settings.
```java
new ComponentBuilder(player.getName()).color(ChatColor.AQUA).event(new ClickEvent(ClickEvent.Action.RUN_COMMAND, "/friends show " + player.getName())).append(" is offline!").color(ChatColor.RED).create();
```

**Comment by minecrafter** [comment]
@md-5: The current ComponentBuilder usage is clunky in some usecases. For example, `event()` is overloaded twice for `ClickEvent` and `HoverEvent`, and casting is required in order to remove these. On the other hand, these functions have clear names that make it apparent what they do.

For example:

    new ComponentBuilder("You're not the owner of this party. Perhaps you meant ")
          .color(ChatColor.RED)
          .append("/p leave")
          .event(new ClickEvent(ClickEvent.Action.RUN_COMMAND, "/p leave"))
          .event(new HoverEvent(HoverEvent.Action.SHOW_TEXT, new ComponentBuilder("Click to leave the party").create()))
          .color(ChatColor.GREEN)
          .append("?")
          .event((ClickEvent) null)
          .event((HoverEvent) null)
          .color(ChatColor.GRAY)
          .create();

With a `reset()` function, I can do this instead:

    new ComponentBuilder("You're not the owner of this party. Perhaps you meant ")
          .color(ChatColor.RED)
          .append("/p leave")
          .event(new ClickEvent(ClickEvent.Action.RUN_COMMAND, "/p leave"))
          .event(new HoverEvent(HoverEvent.Action.SHOW_TEXT, new ComponentBuilder("Click to leave the party").create()))
          .color(ChatColor.GREEN)
          .append("?")
          .reset()
          .color(ChatColor.GRAY)
          .create();

With an extra parameter to `append()`:

    new ComponentBuilder("You're not the owner of this party. Perhaps you meant ")
          .color(ChatColor.RED)
          .append("/p leave")
          .event(new ClickEvent(ClickEvent.Action.RUN_COMMAND, "/p leave"))
          .event(new HoverEvent(HoverEvent.Action.SHOW_TEXT, new ComponentBuilder("Click to leave the party").create()))
          .color(ChatColor.GREEN)
          .append("?", FormatRetention.NONE)
          .color(ChatColor.GRAY)
          .create();

**Comment by minecrafter** [comment]
I am still interested in having this pulled. Pinging @md-5.

**Comment by GingerGeek** [comment]
Seems like a great new feature :+1:

**Comment by pgmann** [comment]
Why has this not been added yet? I really need it :(

Anyone know a workaround for the meantime?

**Comment by md-5** [comment]
I've been on holiday.

Looks fine

**Comment by thinkofdeath** [comment]
Pulled 88e71ead05aa8cc2c810219ce80daff05c01cb3b

**Pull request closed without merging**
