### PR TITLE
Add json configuration provider.

### PR DESCRIPTION
**Pull request by FelixKlauke**
Signed-off-by: Felix Klauke <info@felix-klauke.de>

Add  possibility to use 'Json' as a configuration format. Gson is used for serialization. One arguable section is at https://github.com/SpigotMC/BungeeCord/compare/master...FelixKlauke:feature/json_configuration_provider?expand=1#diff-4dc2d0f3f2770d9269ab7ffad74cf408R52 whats actually needed because the json writer in https://github.com/SpigotMC/BungeeCord/compare/master...FelixKlauke:feature/json_configuration_provider?expand=1#diff-4dc2d0f3f2770d9269ab7ffad74cf408R30 is unable to use correct indents.

Feel free to comment and give feedback, yaml sucks. @md-5 @Thinkofname

### CODE REVIEW

**Comment by Black-Hole** [comment]
You might want to remove those `@author` tags.

**Comment by Janmm14** [comment]
Especially in the ConfigurationProvider class

**Comment by FelixKlauke** [comment]
Done.

**Comment by md-5** [comment]
Ideologies aside (you say yaml sucks, but then you have json as the alternatives which doesn’t even support comments, hardly great for a configuration format), this probably needs to be in a separate module as gson shouldn’t be a requirement (downstream projects which aren’t bungee use this api).

**Comment by md-5** [comment]
Also theres a bunch of pathological tests (i.e. numbered keys) which should also be tested against the json implementation

**Comment by FelixKlauke** [comment]
I think the 'yaml and json suck' discussion is more or less a joke, we shouldn't really discuss this. You're right, there may be some missing tests, I can add all tests you want. 

If GSON should be a dependency is of course arguable. We also have snakeyaml as a corresponding dependency on YAML side. I could offer you switching to org.json as dependency (https://mvnrepository.com/artifact/org.json/json/20180130).

**Comment by md-5** [comment]
GSON is fine as a dependency, it should just be optional

**Comment by FelixKlauke** [comment]
Hm okay, I will seperate the json implementation in a seperate maven module.

**Comment by FelixKlauke** [comment]
When we separate the json implementation into its own module we can't provide an instance of it in the CofigurationProvider. I'd suggest adding a function to the `getProvider(Class<? extends ConfigurationProvider> provider)` method that tries to instantiate the given provider class. Another way would be to let the user define a provider instance.

**Comment by md-5** [comment]
My recommendation would be to have the config provider attempt to load known providers via class.forname and catch class note found fails

**Comment by md-5** [comment]
Went for a more unified implementation, but thanks for the PR nonetheless !

**Pull request closed without merging**
