### PR TITLE
Implemented native code for i386 archs

### PR DESCRIPTION
**Pull request by WolverinDEV**
Implemented native code for i386 archs

### CODE REVIEW

**Comment by ScruffyRules** [comment]
I'd say this is pointless for 99% of the use cases BungeeCord is used in.

**Comment by WolverinDEV** [comment]
I know many dervers who run on 32 bit machines. I also will add windows support soon

**Comment by Black-Hole** [comment]
It's only about 3% that are running x86 server. There's no point in it since every x86 CPU released in the last 12 years is able to run an x64 OS:
http://mcstats.org/global/#System+Arch

**Comment by WolverinDEV** [comment]
Well 3% are still 3000 Servers :)

**Comment by ScruffyRules** [comment]
3000 servers, doesn't say what type of server.

On 4 Oct 2016 08:09, "WolverinDEV" <notifications@github.com<mailto:notifications@github.com>> wrote:

Well 3% are still 3000 Servers :)

**Comment by Black-Hole** [comment]
For BungeeCord it's less than 2%:
http://mcstats.org/plugin/BungeeCord#System+Arch

About 11.5% are running Windows, so native cipher and compression libs for that OS would be nice.

**Comment by ScruffyRules** [comment]
25 are running on x86.
http://mcstats.org/plugin/BungeeCord#System+Arch

**Comment by WolverinDEV** [comment]
@Black-Hole im alredy working on it bute i have some problems to build the dependenc libs

**Comment by camdenorrb** [comment]
I don't think this is much of a sacrifice to make to add compatibility.

**Comment by md-5** [comment]
With compatibility comes support and maintenance though.
Whether its worth all that for an optimisation applicable to < 2% of users who probably don't even need it is debatable.

**Comment by WolverinDEV** [comment]
Okey well. You can close this.
I will make a new puill request when i added Windows support too :)

**Comment by Janmm14** [comment]
@wolverindev you can close your own pr's.

**Comment by WolverinDEV** [comment]
Hubs yes :D

I will create a new one than i added Windows support (x64 (maybe x32))

**Comment by WolverinDEV** [comment]
Hubs yes :D

I will create a new one than i added Windows support (x64 (maybe x32))

**Pull request closed without merging**
