### PR TITLE
Annotate KickStringWriter with @ChannelHandler.Shareable

### PR DESCRIPTION
**Pull request by NayXegp**
Annotate KickStringWriter with the annotation @ChannelHandler.Shareable to use the same instance for all channels.

### CODE REVIEW

**Comment by md-5** [comment]
Whilst I can see what this does, a commit message / description longer than 2 words would be helpful for others reviewing the changelogs etc

**Comment by NayXegp** [comment]
I modified, is it ok ?

**Comment by Mystiflow** [comment]
Just got the redundant import in one file.

**Comment by md-5** [comment]
Thanks

**Pull request closed without merging**
