### PR TITLE
Minecraft 1.20.3 snapshot support

### PR DESCRIPTION
**Pull request by md-5**

### CODE REVIEW

**Comment by Janmm14** [comment]
needs limits for reading nbt

**Comment by Outfluencer** [comment]
we are only reading from server, we dont need limits

**Comment by Janmm14** [comment]
well then some really high limit

**Comment by xism4** [comment]
> we are only reading from server, we dont need limits

Yes, actually a limit it's needed for huge data

**Comment by md-5** [comment]
I will check, but as @Outfluencer I'm pretty sure all of these values are only from the server, are therefore trusted, and consistent with Vanilla, don't have limits.

**Comment by md-5** [comment]
Merged

**Pull request closed without merging**
