### PR TITLE
Queue the handling of Configuration packets

### PR DESCRIPTION
**Pull request by Outfluencer**
Fixes https://github.com/SpigotMC/BungeeCord/issues/3533

### CODE REVIEW

**Comment by md-5** [comment]
Please explain

**Comment by Outfluencer** [comment]
build failed i will explain after fix

**Comment by Outfluencer** [comment]
Okay the configuration packets are droped by the should handle because the server is null.

we need to queue this packets until the server is in configuration state for our connection.

I created a connection between server connector and upstream so i can handle and send the packets to the server if the server is in config state

**Comment by Outfluencer** [comment]
finally compiled xd

**Comment by charonxyz** [comment]
nice!

**Comment by md-5** [comment]
> Okay the configuration packets are droped by the shouldHandle in the upstream because the server is null.

Shouldn't the protocol switch in InitialHandler just be delayed then, like it is for subsequent connections?

**Comment by Outfluencer** [comment]
i am not sure if you can delay it perfectly

**Comment by Outfluencer** [comment]
i think the problem is that packets are dropped until we are connected to a server, i dont sure if we can fix this by delaying something

**Comment by md-5** [comment]
Wouldn't you just take LoginSuccess and move it to where StartConfiguration is in ServerConnector, then make the other consequential adjustments necessary for it to all work?

**Comment by Outfluencer** [comment]
i am not really understanding how you mean

**Comment by md-5** [comment]
See https://github.com/SpigotMC/BungeeCord/pull/3537 (which needs further consideration, just quickly whipped up now)

Although I think undoes effect of f3397b30034795c8b346c07dcfcffbbcbe00eeeb and reintroduces those issues (cc @bob7l)

**Comment by Outfluencer** [comment]
current version works fine

**Pull request closed without merging**
