### PR TITLE
Store last known dimension and don't send useless respawn packets

### PR DESCRIPTION
**Pull request by PunKeel**
In order to improve server switching without lossing the advantages of the Respawn package (reset entities, for instance)

### CODE REVIEW

**Comment by yawkat** [comment]
Please follow bungee code style conventions.

**Comment by PunKeel** [comment]
Is there a way I can apply that convention automatically ? I use Intellij
Idea and already spent more than 10 minutes trying to format my code
according to your "convention"

Thanks.

**Comment by yawkat** [comment]
You can either configure the automatic formatter by hand or do it manually.

**Comment by PunKeel** [comment]
I improved the formatting (using nano instead of my IDE ... haven't found any easy way to change the formatting to use yours), and squashed commits into one (more readable).

Thanks, @yawkat !

**Comment by PaulBGD** [comment]
Been using this patch for a little while now, server switching is a bit faster.

**Comment by Moehritz** [comment]
Works fine (active for several weeks, ~3000 players)

**Comment by PunKeel** [comment]
I was referencing this one, @md-5.
Feel free to lock this conversation too, I won't change my mind: I won't PR anymore on this project.

**Pull request closed without merging**
