### PR TITLE
Fixing 1.20.2 issues

### PR DESCRIPTION
**Pull request by Outfluencer**
Closed https://github.com/SpigotMC/BungeeCord/issues/3527  https://github.com/SpigotMC/BungeeCord/issues/3523

We add some more packet wo be queued and skip packets von states we dont want

### CODE REVIEW

**Comment by md-5** [comment]
Cf 3cb7a12738bcfc1b2b071634f2d10950f8d3c9e8

**Comment by Outfluencer** [comment]
> Cf [3cb7a12](https://github.com/SpigotMC/BungeeCord/commit/3cb7a12738bcfc1b2b071634f2d10950f8d3c9e8)

wow

**Comment by md-5** [comment]
?

**Comment by Outfluencer** [comment]
what means cf?

**Comment by md-5** [comment]
Compare. What bits of this are still needed?

**Comment by Outfluencer** [comment]
i think the queueing of Tblist packets

**Comment by Outfluencer** [comment]
i am testing it while i am writing with you right now xd

**Comment by Outfluencer** [comment]
okay everything is wokring

**Comment by Outfluencer** [comment]
works now

**Pull request closed without merging**
